## Imports

In [2]:
import pandas as pd
import functions as fn

In [3]:
# dataset setup
reset =  False

if reset:
    # Read in original data
    l_shooting = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "League Shooting", header = 11, index_col = 0).reset_index(drop=True)
    l_passing = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "League Passing", header = 11, index_col = 0).reset_index(drop=True)
    l_defense = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "League Defense", header = 11, index_col = 0).reset_index(drop=True)
    l_goalkeeping = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "League Goalkeeping", header = 11, index_col = 0).reset_index(drop=True)
    t_shooting = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "Tournament Shooting", header = 11, index_col = 0).reset_index(drop=True)
    t_passing = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "Tournament Passing", header = 11, index_col = 0).reset_index(drop=True)
    t_defense = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "Tournament Defense", header = 11, index_col = 0).reset_index(drop=True)
    t_goalkeeping = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "Tournament Goalkeeping", header = 11, index_col = 0).reset_index(drop=True)
    salary_2020 = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "2020 Salaries", header = 11, index_col = 0).reset_index(drop=True)
    salary_2021 = pd.read_excel(r"../data/raw-data/2022-student-research-case-study-player-data.xlsx", "2021 Salaries", header = 11, index_col = 0).reset_index(drop=True)



    l_shooting.to_csv(r"../data/player-data/l_shooting.csv")
    l_passing.to_csv(r"../data/player-data/l_passing.csv")
    l_defense.to_csv(r"../data/player-data/l_defense.csv")
    l_goalkeeping.to_csv(r"../data/player-data/l_goalkeeping.csv")
    t_shooting.to_csv(r"../data/player-data/t_shooting.csv")
    t_passing.to_csv(r"../data/player-data/t_passing.csv")
    t_defense.to_csv(r"../data/player-data/t_defense.csv")
    t_goalkeeping.to_csv(r"../data/player-data/t_goalkeeping.csv")
    salary_2020.to_csv(r"../data/player-data/salary_2020.csv")
    salary_2021.to_csv(r"../data/player-data/salary_2021.csv")

else:
    l_shooting = pd.read_csv(r"../data/player-data/l_shooting.csv", index_col=0)
    l_passing = pd.read_csv(r"../data/player-data/l_passing.csv", index_col=0)
    l_defense = pd.read_csv(r"../data/player-data/l_defense.csv", index_col=0)
    l_goalkeeping = pd.read_csv(r"../data/player-data/l_goalkeeping.csv", index_col=0)
    t_shooting = pd.read_csv(r"../data/player-data/t_shooting.csv", index_col=0)
    t_passing = pd.read_csv(r"../data/player-data/t_passing.csv", index_col=0)
    t_defense = pd.read_csv(r"../data/player-data/t_defense.csv", index_col=0)
    t_goalkeeping = pd.read_csv(r"../data/player-data/t_goalkeeping.csv", index_col=0)
    salary_2020 = pd.read_csv(r"../data/player-data/salary_2020.csv", index_col=0)
    salary_2021 = pd.read_csv(r"../data/player-data/salary_2021.csv", index_col=0)


all_df = [l_shooting, l_passing, l_defense, l_goalkeeping, t_shooting, t_passing, t_defense, t_goalkeeping]

## Data Checks

In [ ]:
print(sorted(l_shooting.columns.drop('Squad')) == sorted(t_shooting.columns))
print(sorted(l_passing.columns.drop('Squad')) == sorted(t_passing.columns))
print(sorted(l_defense.columns.drop('Squad')) == sorted(t_defense.columns))
print(sorted(l_goalkeeping.columns.drop('Squad')) == sorted(t_goalkeeping.columns))

True
True
True
True

## Shooting Columns

Descriptive
    'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'League', 'Year'
Metrics
    '90s', 'Gls', 'Standard Sh', 'Standard SoT', 'Standard SoT%', 'Standard Sh/90', 'Standard SoT/90', 'Standard G/Sh', 'Standard G/SoT', 'Standard Dist', 'Standard FK', 
    'Performance PK', 'Performance PKatt',
    'Expected xG', 'Expected npxG', 'Expected npxG/Sh', 'Expected G-xG', 'Expected np:G-xG'

## Passing Columns

Descriptive
       'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'League', 'Year'

Metrics
       'Total Cmp', 'Total Att', 'Total Cmp%', 'Total TotDist', 'Total PrgDist',
       'Short Cmp', 'Short Att', 'Short Cmp%', 'Medium Cmp', 'Medium Att',
       'Medium Cmp%', 'Long Cmp', 'Long Att', 'Long Cmp%', 'Ast', 'xA', 'A-xA',
       'KP', '1/3', 'PPA', 'CrsPA', 'Prog', 

## Defense Columns

Descriptive
       'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'League', 'Year'
       
Metrics
       'Tackles Tkl','Tackles TklW', 'Tackles Def 3rd', 'Tackles Mid 3rd', 'Tackles Att 3rd',
       'Vs Dribbles Tkl', 'Vs Dribbles Att', 'Vs Dribbles Tkl%',
       'Vs Dribbles Past', 'Pressures Press', 'Pressures Succ', 'Pressures %',
       'Pressures Def 3rd', 'Pressures Mid 3rd', 'Pressures Att 3rd',
       'Blocks Blocks', 'Blocks Sh', 'Blocks ShSv', 'Blocks Pass', 'Int',
       'Tkl+Int', 'Clr', 'Err', 

## Goalkeeping

Decsriptive
       'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'League', 'Year'
       
Metrics
       'Playing Time MP','Playing Time Starts', 'Playing Time Min', 'Playing Time 90s',
       'Performance GA', 'Performance GA90', 'Performance SoTA',
       'Performance Saves', 'Performance Save%', 'W', 'D', 'L',
       'Performance CS', 'Performance CS%', 'Performance PKatt',
       'Penalty Kicks PKA', 'Penalty Kicks PKsv', 'Penalty Kicks PKm', 'Penalty Kicks Save%',

## Data Preparation

In [4]:
# Processing to all dataframes

for df in all_df:
    df['Player'] = df['Player'].apply(lambda x: fn.clean_names(x), 0)
    fn.pos_to_onehot(df)

salary_2020['Player Name'] = salary_2020['Player Name'].apply(lambda x: fn.clean_names(x), 0)
salary_2021['Player Name'] = salary_2021['Player Name'].apply(lambda x: fn.clean_names(x), 0)

In [ ]:
# Player age data query

print((l_shooting['Age'][l_shooting.Year == 2020] + l_shooting['Born'][l_shooting.Year == 2020]).describe())
print((l_defense['Age'][l_defense.Year == 2020] + l_defense['Born'][l_defense.Year == 2020]).describe())
print((l_goalkeeping['Age'][l_goalkeeping.Year == 2020] + l_goalkeeping['Born'][l_goalkeeping.Year == 2020]).describe())
print((l_passing['Age'][l_passing.Year == 2020] + l_passing['Born'][l_passing.Year == 2020]).describe())

count    2732.000000
mean     2018.650073
std         0.477034
min      2018.000000
25%      2018.000000
50%      2019.000000
75%      2019.000000
max      2019.000000
dtype: float64
count    2732.000000
mean     2018.650073
std         0.477034
min      2018.000000
25%      2018.000000
50%      2019.000000
75%      2019.000000
max      2019.000000
dtype: float64
count     205.000000
mean     2018.707317
std         0.456108
min      2018.000000
25%      2018.000000
50%      2019.000000
75%      2019.000000
max      2019.000000
dtype: float64
count    2732.000000
mean     2018.650073
std         0.477034
min      2018.000000
25%      2018.000000
50%      2019.000000
75%      2019.000000
max      2019.000000
dtype: float64

In [ ]:
# Compare players between years

for df in all_df:
    df_2020 = df['Player'][df.Year == 2020]
    df_2021 = df['Player'][df.Year == 2021]

    leaving = df_2020[~df_2020.isin(df_2021)]
    entering = df_2021[~df_2021.isin(df_2020)]

    print(f'{df=}'.split('=')[0])
    print(f"{len(df_2020)} total players in 2020, {len(df_2021)} total players in 2021")
    print(f"{len(leaving)} players left in 2020, {len(entering)} players joined in 2021.")

df
2732 total players in 2020, 2822 total players in 2021
748 players left in 2020, 822 players joined in 2021.
df
2732 total players in 2020, 2822 total players in 2021
748 players left in 2020, 822 players joined in 2021.
df
2732 total players in 2020, 2822 total players in 2021
748 players left in 2020, 822 players joined in 2021.
df
205 total players in 2020, 208 total players in 2021
65 players left in 2020, 68 players joined in 2021.
df
1527 total players in 2020, 488 total players in 2021
1115 players left in 2020, 76 players joined in 2021.
df
0 total players in 2020, 488 total players in 2021
0 players left in 2020, 488 players joined in 2021.
df
0 total players in 2020, 488 total players in 2021
0 players left in 2020, 488 players joined in 2021.
df
104 total players in 2020, 25 total players in 2021
84 players left in 2020, 5 players joined in 2021.

In [ ]:
l_shooting.describe()
# l_passing.describe()
# l_defense.describe()
# l_goalkeeping.describe()
# t_shooting.describe()
# t_passing.describe()
# t_defense.describe()
# t_goalkeeping.describe()

,FW,MF,DF,GK,Age,Born,90s,Gls,Standard Sh,Standard SoT,...,Standard Dist,Standard FK,Performance PK,Performance PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG,Year
count,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,...,4523.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,4523.000000,5554.000000,5554.000000,5554.000000
mean,0.344076,0.456068,0.392330,0.074361,25.248109,1993.913576,14.031062,0.111251,1.154498,0.367137,...,17.340803,0.044771,0.009950,0.013668,0.122649,0.111151,0.090615,-0.012285,-0.011298,2020.508102
std,0.475109,0.498111,0.488313,0.262381,4.553069,4.581151,10.808880,0.276028,1.359627,0.564463,...,5.775997,0.256818,0.087583,0.091131,0.195576,0.182014,0.082497,0.227753,0.227812,0.499979
min,0.000000,0.000000,0.000000,0.000000,14.000000,1977.000000,-0.100000,-0.100000,-0.100000,-0.100000,...,1.360000,-0.100000,-0.100000,-0.100000,-0.100000,-0.100000,-0.080000,-4.100000,-4.080000,2020.000000
25%,0.000000,0.000000,0.000000,0.000000,22.000000,1991.000000,3.860000,-0.010000,0.260000,0.040000,...,13.190000,-0.040000,-0.050000,-0.040000,0.010000,0.000000,0.030000,-0.070000,-0.070000,2020.000000
50%,0.000000,0.000000,0.000000,0.000000,25.000000,1994.000000,12.885000,0.060000,0.780000,0.180000,...,17.160000,0.020000,0.010000,0.010000,0.080000,0.070000,0.090000,-0.010000,-0.010000,2021.000000
75%,1.000000,1.000000,1.000000,0.000000,28.000000,1997.000000,22.797500,0.150000,1.740000,0.560000,...,21.075000,0.070000,0.060000,0.060000,0.170000,0.170000,0.140000,0.050000,0.050000,2021.000000
max,1.000000,1.000000,1.000000,1.000000,42.000000,2005.000000,38.100000,9.960000,30.040000,10.100000,...,74.080000,10.010000,3.360000,3.300000,4.010000,4.090000,0.770000,10.060000,10.070000,2021.000000

In [ ]:
print(l_shooting['Pos'].isnull().sum())
print(l_passing['Pos'].isnull().sum())
print(l_defense['Pos'].isnull().sum())
print(l_goalkeeping['Pos'].isnull().sum())
print(t_shooting['Pos'].isnull().sum())
print(t_passing['Pos'].isnull().sum())
print(t_defense['Pos'].isnull().sum())
print(t_goalkeeping['Pos'].isnull().sum())

0
0
0
0
0
0
1
0

In [5]:
# Save all

filenames = [
    "l_shooting_clean.csv",
    "l_passing_clean.csv",
    "l_defense_clean.csv",
    "l_goalkeeping_clean.csv",
    "t_shooting_clean.csv",
    "t_passing_clean.csv",
    "t_defense_clean.csv",
    "t_goalkeeping_clean.csv"
]
salary_2020.to_csv("../data/processed-data/salary_2020.csv")
salary_2021.to_csv("../data/processed-data/salary_2021.csv")


for index, df in enumerate(all_df):
    df.to_csv("../data/processed-data/" + filenames[index])